# POST  http://localhost:8000/auth/register/
# Content-Type: application/json

# {
#     "firstName": "Samson",
#     "lastName": "Amos",
#     "email":"v3dent@gmail.com",
#     "password":"Chelsea24462!"
# }

# POST http://localhost:8000/auth/login/
# Content-Type: application/json

# {
#    "email":"v3dent@gmail.com",
#    "password":"Chelsea24462!" 
# }

# PUT  http://localhost:8000/auth/change-password/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY3NzA4MzM5MywiZXhwIjoxNjc3MDg0MjkzfQ.jHte5qTPGY7ZmgSUbA8dU_w-rATOOhCmix33OjwtOlE

# {
#     "currentPassword": "Spotify24462!",
#     "newPassword": "Chelsea24462!"
# }

# POST  http://localhost:8000/auth/forgot-password/
# Content-Type: application/json

# {
#     "email" : "v3dent@gmail.com"
# }